import importlib.util
import unittest
from pathlib import Path

spec = importlib.util.spec_from_file_location("authorship", Path(__file__).with_name("check-authorship.py"))
auth = importlib.util.module_from_spec(spec)
spec.loader.exec_module(auth)


class AuthorshipPolicyTest(unittest.TestCase):
    def test_plain_content_mentions_are_allowed(self):
        for text in ["Fix Claude API rendering", "Discuss Claude, Codex and OpenAI integration", "The example was generated with Claude to reproduce this bug."]:
            self.assertFalse(auth.signature_line(text))

    def test_human_coauthor_is_preserved(self):
        self.assertFalse(auth.signature_line("Co-Authored-By: Owen Lin <reader@example.com>"))
        self.assertFalse(auth.tool_identity("Claude Shannon <reader@example.com> 123456 +0800"))

    def test_tool_metadata_and_signatures_are_rejected(self):
        for text in ["Co-Authored-By: Claude <noreply@anthropic.com>", "🤖 Generated with [Claude Code](https://claude.ai/code)", "Generated by Codex", "Author: ChatGPT"]:
            self.assertTrue(auth.signature_line(text))
        self.assertTrue(auth.tool_identity("Claude <noreply@anthropic.com> 123456 +0800"))
        self.assertTrue(auth.tool_identity("OpenAI Codex <codex@openai.com> 123456 +0800"))

    def test_only_signature_bytes_are_removed(self):
        raw = b"Fix Claude API\r\n\r\nCo-Authored-By: Claude <noreply@anthropic.com>\r\n\r\nBody unchanged.\n"
        cleaned, removed = auth.clean_message(raw)
        self.assertEqual(cleaned, b"Fix Claude API\r\n\r\n\r\nBody unchanged.\n")
        self.assertEqual(len(removed), 1)


if __name__ == "__main__":
    unittest.main()
