import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { chromium } from 'playwright';
import { createWriterServer } from './server.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const project = path.resolve(here, '../..');
const require = createRequire(import.meta.url);
const { renderMarkdown } = require('../../lib/markdown.cjs');
const fixtures = path.join(here, '.fixtures');
await fs.mkdir(fixtures, { recursive: true });
const root = await fs.mkdtemp(path.join(fixtures, 'browser-'));
await fs.mkdir(path.join(root, 'source', '_posts'), { recursive: true });
await fs.mkdir(path.join(root, 'source', '_drafts'), { recursive: true });
await fs.mkdir(path.join(root, 'themes', 'owen', 'source', 'css'), { recursive: true });
await fs.cp(path.join(project, 'themes', 'owen', 'source', 'vendor'), path.join(root, 'themes', 'owen', 'source', 'vendor'), { recursive: true });
await fs.copyFile(path.join(project, 'themes', 'owen', 'source', 'css', 'site.css'), path.join(root, 'themes', 'owen', 'source', 'css', 'site.css'));
const source = '---\ntitle: 寫作桌驗證\ntitle_en: "Writer check"\ndate: 2026-10-01 08:00:00\n---\n\n<!-- LANG:ZH START -->\n## 一篇新文章\n\n在 Markdown 中寫下思考，圖片留在自己的網站。\n\n| 項目 | 結果 |\n| --- | --- |\n| 草稿 | 保留在本機 |\n\n數學：$x^2 + y^2 = z^2$。\n\n```python\nprint("hello")\n```\n<!-- LANG:ZH END -->\n<!-- LANG:EN START -->\n## An English article\n\nMarkdown, with images kept on your own website.\n<!-- LANG:EN END -->\n<script>parent.document.body.dataset.compromised="yes"</script>\n';
await fs.writeFile(path.join(root, 'source', '_posts', '測試文章.md'), source);
const { server, store } = await createWriterServer({ projectRoot: root, renderMarkdown });
let appRequests = 0;
server.on('request', (request) => { if (request.url === '/app.js') appRequests += 1; });
await new Promise((resolve, reject) => { server.once('error', reject); server.listen(0, '127.0.0.1', resolve); });
let browser;
const errors = [];
try {
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/`);
  await page.getByRole('button', { name: '測試文章', exact: true }).click();
  const frame = page.frameLocator('#preview');
  await frame.getByRole('heading', { name: '一篇新文章' }).waitFor();
  assert.equal(await page.evaluate(() => document.body.dataset.compromised), undefined);
  assert.equal(await frame.locator('body').evaluate((element) => getComputedStyle(element).paddingTop), '28px');
  assert.ok(await frame.locator('.katex').count());
  assert.equal(await frame.locator('.katex').evaluate((element) => getComputedStyle(element).fontFamily.includes('KaTeX')), true);
  const mathGeometry = await frame.locator('.katex-html').first().evaluate((element) => {
    const leaves = [...element.querySelectorAll('span')].filter((span) => !span.childElementCount);
    const base = leaves.find((span) => span.textContent.trim() === 'x').getBoundingClientRect();
    const exponent = leaves.find((span) => span.textContent.trim() === '2').getBoundingClientRect();
    return { baseCenter: base.top + base.height / 2, exponentCenter: exponent.top + exponent.height / 2 };
  });
  assert.ok(mathGeometry.exponentCenter < mathGeometry.baseCenter - 2, `Exponent must appear above the base: ${JSON.stringify(mathGeometry)}`);
  await page.locator('#preview-language').selectOption('en');
  await frame.getByRole('heading', { name: 'An English article' }).waitFor();
  await frame.getByRole('heading', { name: 'Writer check', exact: true }).waitFor();
  assert.equal(await frame.getByRole('heading', { name: '一篇新文章' }).isVisible(), false);
  await page.locator('#preview-language').selectOption('zh');
  await frame.getByRole('heading', { name: '一篇新文章' }).waitFor();
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aYl8AAAAASUVORK5CYII=', 'base64');
  await page.locator('#image-input').setInputFiles({ name: '範例.png', mimeType: 'image/png', buffer: png });
  await page.waitForFunction(() => document.getElementById('editor').value.includes('/images/uploads/'));
  await frame.getByRole('img', { name: '範例' }).waitFor();
  assert.equal(await frame.getByRole('img', { name: '範例' }).evaluate((element) => element.complete && element.naturalWidth), 1);
  await page.locator('#editor').evaluate((element, bytes) => {
    element.focus();
    element.setSelectionRange(element.value.length, element.value.length);
    const transfer = new DataTransfer();
    transfer.items.add(new File([new Uint8Array(bytes)], '剪貼簿.png', { type: 'image/png' }));
    element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: transfer, bubbles: true, cancelable: true }));
  }, [...png]);
  await page.waitForFunction(() => document.getElementById('editor').value.includes('![剪貼簿]'));
  await page.locator('#editor').evaluate((element, bytes) => {
    element.setSelectionRange(element.value.length, element.value.length);
    const transfer = new DataTransfer();
    transfer.items.add(new File([new Uint8Array(bytes)], '拖入.png', { type: 'image/png' }));
    element.dispatchEvent(new DragEvent('drop', { dataTransfer: transfer, bubbles: true, cancelable: true }));
  }, [...png]);
  await page.waitForFunction(() => document.getElementById('editor').value.includes('![拖入]'));
  await page.getByRole('button', { name: '儲存', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('status').textContent.startsWith('已儲存'));
  const saved = await store.read('posts/測試文章.md');
  assert.ok(saved.content.includes('![範例](/images/uploads/'));
  assert.ok(saved.content.includes('![剪貼簿](/images/uploads/'));
  assert.ok(saved.content.includes('![拖入](/images/uploads/'));
  assert.ok(saved.content.includes('<script>parent.document.body.dataset.compromised="yes"</script>'));
  await page.screenshot({ path: path.join(root, 'desktop.png'), fullPage: true });
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    await page.getByRole('tab', { name: '預覽', exact: true }).click();
    assert.equal(await page.getByRole('button', { name: '加入圖片', exact: true }).isVisible(), true);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `${width}px viewport must not overflow`);
    await page.screenshot({ path: path.join(root, `mobile-${width}.png`), fullPage: true });
  }
  await page.getByRole('button', { name: '新增草稿', exact: true }).click();
  await page.getByRole('textbox', { name: '文章標題', exact: true }).fill('瀏覽器草稿驗證');
  await page.getByRole('button', { name: '建立草稿', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('document-name').textContent === '瀏覽器草稿驗證.md');
  assert.equal((await store.list()).filter((item) => item.kind === 'posts').length, 1);
  assert.equal((await store.list()).filter((item) => item.kind === 'drafts').length, 1);
  await page.setViewportSize({ width: 1440, height: 900 });
  const longSource = '---\ntitle: 長文捲動驗證\n---\n\n## 長文內容\n\n' + Array.from({ length: 80 }, (_, index) => `第 ${index + 1} 段，保留文章預覽的閱讀位置。`).join('\n\n') + '\n\n<script>parent.document.body.dataset.inlineProbe="yes"</script>\n<script src="/app.js"></script>\n<img alt="事件處理測試" src="/images/absent.png" onerror="parent.document.body.dataset.eventProbe=\'yes\'">\n<iframe src="/"></iframe>\n<form action="/api/drafts" method="post"><input name="title" value="不應建立"><button type="submit">表單測試</button></form>\n';
  await page.locator('#editor').fill(longSource);
  await frame.getByRole('heading', { name: '長文內容', exact: true }).waitFor();
  await page.locator('#preview').evaluate((element) => element.contentWindow.scrollTo(0, 700));
  const scrollBefore = await page.locator('#preview').evaluate((element) => element.contentWindow.scrollY);
  await page.locator('#editor').fill(longSource + '\n\n編輯後新增的段落。\n');
  await frame.getByText('編輯後新增的段落。', { exact: true }).waitFor();
  await page.waitForFunction((expected) => Math.abs(document.getElementById('preview').contentWindow.scrollY - expected) < 4, scrollBefore);
  const scrollAfter = await page.locator('#preview').evaluate((element) => element.contentWindow.scrollY);
  assert.ok(Math.abs(scrollAfter - scrollBefore) < 4, `Preview scroll must survive edits: ${scrollBefore} → ${scrollAfter}`);
  await page.waitForFunction(() => document.getElementById('preview').contentDocument.querySelector('img')?.complete);
  assert.deepEqual(await page.evaluate(() => ({ inline: document.body.dataset.inlineProbe ?? null, event: document.body.dataset.eventProbe ?? null })), { inline: null, event: null });
  assert.equal(appRequests, 1, 'Preview must not fetch or execute the authored external script');
  await frame.getByRole('button', { name: '表單測試', exact: true }).click();
  assert.equal((await store.list()).filter((item) => item.kind === 'drafts').length, 1, 'Preview forms must not create files');
  assert.equal(await page.evaluate(async () => (await fetch('/api/library')).status), 403, 'Even same-origin requests still require the startup token');
  await page.locator('#editor').fill('---\ntitle: 標記錯誤驗證\n---\n\n<!-- LANG:ZH START -->\n正文');
  await page.getByRole('alert').filter({ hasText: '雙語標記缺少配對' }).waitFor();
  assert.deepEqual(errors, []);
  const receipt = { passed: true, root, katexVersion: require('katex/package.json').version, mathGeometry, previewScroll: { before: scrollBefore, after: scrollAfter }, checks: ['production renderer', 'sandbox inline/event/external scripts blocked', 'preview forms blocked', 'same-origin API still requires token', 'iframe CSS and KaTeX font', 'superscript above base', 'bilingual body and title preview', 'image attachment', 'clipboard paste handler', 'image drop handler', 'explicit save and revisions', '390/320px no overflow', 'draft does not publish', 'preview scroll retained', 'bilingual syntax error explains correction'], pageErrors: errors };
  await fs.writeFile(path.join(root, 'receipt.json'), JSON.stringify(receipt, null, 2));
  console.log(JSON.stringify(receipt, null, 2));
} finally {
  await browser?.close();
  await new Promise((resolve) => { server.close(resolve); server.closeAllConnections(); });
}
