import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { chromium } from 'playwright';
import { createWriterServer } from './server.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const { renderMarkdown } = require('../../lib/markdown.cjs');
const fixtures = path.join(here, '.fixtures');
await fs.mkdir(fixtures, { recursive: true });
const root = await fs.mkdtemp(path.join(fixtures, 'recovery-'));
const source = '---\ntitle: 備份驗證\n---\n\n## 原稿\n\n原有文字。\n';
const filename = path.join(root, 'source', '_posts', '備份驗證.md');
await fs.mkdir(path.dirname(filename), { recursive: true });
await fs.mkdir(path.join(root, 'source', '_drafts'), { recursive: true });
await fs.mkdir(path.join(root, 'themes', 'owen', 'source'), { recursive: true });
await fs.cp(path.resolve(here, '../../themes/owen/source/vendor'), path.join(root, 'themes', 'owen', 'source', 'vendor'), { recursive: true });
await fs.cp(path.resolve(here, '../../themes/owen/source/css'), path.join(root, 'themes', 'owen', 'source', 'css'), { recursive: true });
await fs.writeFile(filename, source);
await fs.writeFile(path.join(path.dirname(filename), '切換驗證.md'), source);
let { server } = await createWriterServer({ projectRoot: root, renderMarkdown });
const listen = (port = 0) => new Promise((resolve, reject) => { server.once('error', reject); server.listen(port, '127.0.0.1', resolve); });
const stop = () => new Promise((resolve) => { server.close(resolve); server.closeAllConnections(); });
await listen();
const port = server.address().port, origin = `http://127.0.0.1:${port}`;
const checks = [], errors = [], failures = [], intentionalFailures = [];
let browser;
let rotatedFixtureToken;
const meta = process.platform === 'darwin' ? 'Meta' : 'Control';
const png = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGMwjw/6DwADoQHoRkGVTQAAAABJRU5ErkJggg==';
try {
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, permissions: ['clipboard-read', 'clipboard-write'] });
  context.on('page', (page) => {
    page.on('pageerror', (error) => errors.push(error.message));
    page.on('dialog', (dialog) => dialog.accept());
  });
  context.on('response', (response) => {
    if (!response.url().startsWith(origin) || response.status() < 400) return;
    const failure = { path: new URL(response.url()).pathname, status: response.status(), method: response.request().method() };
    const staleFixtureRequest = rotatedFixtureToken && response.request().headers()['x-writer-token'] === rotatedFixtureToken;
    if (failure.path === '/api/document' && failure.status === 409 || ['/api/document', '/api/preview'].includes(failure.path) && failure.status === 403 && staleFixtureRequest) intentionalFailures.push(failure);
    else failures.push(failure);
  });
  const page = await context.newPage();
  const editor = page.locator('#editor');
  const loaded = async (target = page) => { await target.waitForFunction(() => !document.getElementById('editor').disabled); };
  await page.goto(origin);
  await page.getByRole('button', { name: '備份驗證', exact: true }).click();
  await loaded();
  await editor.focus();
  await editor.evaluate((element) => element.setSelectionRange(element.value.length, element.value.length));
  await page.keyboard.type('鍵盤輸入的文字。\n');
  const beforeImage = await editor.inputValue();
  await page.evaluate(async (data) => {
    const bytes = Uint8Array.from(atob(data), (character) => character.charCodeAt(0));
    await navigator.clipboard.write([new ClipboardItem({ 'image/png': new Blob([bytes], { type: 'image/png' }) })]);
  }, png);
  await page.keyboard.press(`${meta}+v`);
  await page.waitForFunction(() => /!\[.*\]\(\/images\/uploads\/.+\.png\)/.test(document.getElementById('editor').value));
  const withImage = await editor.inputValue();
  await page.keyboard.press(`${meta}+z`);
  assert.equal(await editor.inputValue(), beforeImage);
  checks.push('real clipboard image undo preserves previous keyboard text');
  await page.keyboard.press(`${meta}+Shift+z`);
  assert.equal(await editor.inputValue(), withImage);
  checks.push('real clipboard image redo restores exact Markdown');
  await page.getByRole('button', { name: '切換驗證', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('document-name').textContent === '切換驗證.md');
  await page.getByRole('button', { name: '備份驗證', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('document-name').textContent === '備份驗證.md');
  await page.getByRole('button', { name: '還原到編輯區', exact: true }).click();
  assert.equal(await editor.inputValue(), withImage);
  assert.ok(await page.evaluate((content) => Object.keys(localStorage).filter((key) => key.includes('recovery')).map((key) => JSON.parse(localStorage.getItem(key))).some((record) => record.status === 'pending' && record.content === content), withImage));
  checks.push('same-tab document round-trip recovery retains its own pending record');

  assert.equal(await fs.readFile(filename, 'utf8'), source);
  checks.push('browser backup never saves the source implicitly');
  await page.reload(); await loaded();
  assert.equal(await editor.inputValue(), source);
  await page.locator('#recovery').waitFor({ state: 'visible' });
  assert.ok((await page.locator('#recovery-note').textContent()).includes('原始檔案'));
  checks.push('reload reopens the last document and offers explicit recovery');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '下載備份', exact: true }).click();
  const download = await downloadPromise;
  const stream = await download.createReadStream();
  const chunks = []; for await (const chunk of stream) chunks.push(chunk);
  assert.equal(Buffer.concat(chunks).toString('utf8'), withImage);
  checks.push('backup download retains Unicode and the uploaded image reference');
  await page.getByRole('button', { name: '還原到編輯區', exact: true }).click();
  assert.equal(await editor.inputValue(), withImage);
  assert.equal(await fs.readFile(filename, 'utf8'), source);
  checks.push('explicit recovery restores the buffer without altering source');
  await page.close();
  const reopened = await context.newPage();
  await reopened.goto(origin); await loaded(reopened);
  await reopened.getByRole('button', { name: '還原到編輯區', exact: true }).click();
  assert.equal(await reopened.locator('#editor').inputValue(), withImage);
  checks.push('closing and reopening a tab retains unsaved Markdown');
  rotatedFixtureToken = await reopened.locator('meta[name=writer-token]').getAttribute('content');
  await stop();
  ({ server } = await createWriterServer({ projectRoot: root, renderMarkdown }));
  await listen(port);
  await reopened.getByRole('button', { name: '儲存', exact: true }).click();
  await reopened.getByRole('alert').waitFor({ state: 'visible' });
  assert.equal(await reopened.locator('#editor').inputValue(), withImage);
  await reopened.reload(); await loaded(reopened);
  await reopened.getByRole('button', { name: '還原到編輯區', exact: true }).click();
  assert.equal(await reopened.locator('#editor').inputValue(), withImage);
  checks.push('server token rotation and reload preserve the recoverable buffer');
  await fs.writeFile(filename, source + '\n其他編輯器的新內容。\n');
  await reopened.reload(); await loaded(reopened);
  assert.ok((await reopened.locator('#recovery-note').textContent()).includes('其他修改'));
  await reopened.getByRole('button', { name: '還原到編輯區', exact: true }).click();
  await reopened.getByRole('button', { name: '儲存', exact: true }).click();
  await reopened.getByRole('alert').waitFor({ state: 'visible' });
  assert.equal(await fs.readFile(filename, 'utf8'), source + '\n其他編輯器的新內容。\n');
  checks.push('recovery retains the old version and refuses to overwrite external changes');
  const other = await context.newPage(); await other.goto(origin); await loaded(other);
  await other.locator('#editor').fill(source + '\n另一個頁籤的內容。\n');
  await other.getByRole('button', { name: '切換驗證', exact: true }).click();
  await other.waitForFunction(() => document.getElementById('document-name').textContent === '切換驗證.md');
  await reopened.reload(); await loaded(reopened);
  assert.ok(await reopened.locator('#recovery-choice option').count() >= 2);
  checks.push('independent tabs retain distinct selectable recovery records');
  assert.equal(await reopened.locator('#document-name').textContent(), '備份驗證.md');
  checks.push('reloading one tab retains its document when another tab switches files');
  const pendingBefore = await reopened.evaluate(() => Object.keys(localStorage).filter((key) => key.includes('recovery')).map((key) => JSON.parse(localStorage.getItem(key))).filter((record) => record.status === 'pending').length);
  await reopened.getByRole('button', { name: '保留目前檔案', exact: true }).click();
  const afterDismiss = await reopened.evaluate(() => Object.keys(localStorage).filter((key) => key.includes('recovery')).map((key) => JSON.parse(localStorage.getItem(key))));
  assert.ok(afterDismiss.some((record) => record.status === 'dismissed' && record.content));
  assert.equal(afterDismiss.filter((record) => record.status === 'pending').length, pendingBefore - 1);
  checks.push('keeping the source retains dismissed backup bytes');
  for (const width of [320, 390]) {
    await reopened.setViewportSize({ width, height: 844 });
    assert.equal(await reopened.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  }
  checks.push('recovery controls remain within 320 and 390 pixel viewports');
  const quota = await browser.newContext();
  await quota.addInitScript(() => { Storage.prototype.setItem = function () { throw new DOMException('Quota exceeded', 'QuotaExceededError'); }; });
  const quotaPage = await quota.newPage(); await quotaPage.goto(origin);
  await quotaPage.getByRole('button', { name: '備份驗證', exact: true }).click(); await loaded(quotaPage);
  await quotaPage.locator('#editor').fill(source + '配額失敗仍可編輯。');
  assert.ok((await quotaPage.locator('#status').textContent()).includes('備份無法使用'));
  assert.equal(await quotaPage.getByRole('button', { name: '儲存', exact: true }).isEnabled(), true);
  await quotaPage.getByRole('button', { name: '儲存', exact: true }).click();
  await quotaPage.waitForFunction(() => document.getElementById('save').disabled && document.getElementById('status').textContent.includes('已儲存'));
  assert.equal(await fs.readFile(filename, 'utf8'), source + '配額失敗仍可編輯。');
  checks.push('storage quota failure leaves editing and explicit saving available');
  const currentDownloadPromise = quotaPage.waitForEvent('download');
  await quotaPage.getByRole('button', { name: '下載 Markdown', exact: true }).click();
  const currentDownload = await currentDownloadPromise;
  const currentChunks = []; for await (const chunk of await currentDownload.createReadStream()) currentChunks.push(chunk);
  assert.equal(Buffer.concat(currentChunks).toString('utf8'), source + '配額失敗仍可編輯。');
  checks.push('current-buffer download works even when browser backup is unavailable');

  await quota.close();
  const cleanContext = await browser.newContext();
  const cleanPage = await cleanContext.newPage(); await cleanPage.goto(origin);
  await cleanPage.getByRole('button', { name: '備份驗證', exact: true }).click(); await loaded(cleanPage);
  await cleanPage.locator('#editor').focus();
  await cleanPage.locator('#editor').evaluate((element) => element.setSelectionRange(element.value.length, element.value.length));
  await cleanPage.keyboard.type('稍後撤銷的文字。');
  for (let attempt = 0; attempt < 12 && await cleanPage.locator('#editor').inputValue() !== source + '配額失敗仍可編輯。'; attempt += 1) await cleanPage.keyboard.press(`${meta}+z`);
  assert.equal(await cleanPage.locator('#editor').inputValue(), source + '配額失敗仍可編輯。');
  await cleanPage.reload(); await loaded(cleanPage);
  assert.equal(await cleanPage.locator('#recovery').isVisible(), false);
  checks.push('undoing back to the saved source retires the superseded dirty backup');
  await cleanContext.close();

  await reopened.screenshot({ path: path.join(root, 'recovery-390.png'), fullPage: true });
  assert.deepEqual(errors, []); assert.deepEqual(failures, []);
  const receipt = { passed: true, root, checks, pageErrors: errors, localFailures: failures, intentionalFailures };
  await fs.writeFile(path.join(root, 'receipt.json'), JSON.stringify(receipt, null, 2));
  console.log(JSON.stringify(receipt));
} catch (error) {
  await fs.writeFile(path.join(root, 'failure.json'), JSON.stringify({ passed: false, error: error.message, checks, errors, failures, intentionalFailures }, null, 2));
  console.error(JSON.stringify({ root, error: error.message, checks })); throw error;
} finally { await browser?.close(); await stop(); }
